// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetsHandlerForTest() {
  return window['go']['app']['App']['AssetsHandlerForTest']();
}

export function ResolveLive(arg1, arg2) {
  return window['go']['app']['App']['ResolveLive'](arg1, arg2);
}

export function SetClientSize(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetClientSize'](arg1, arg2, arg3, arg4);
}

export function StartupForTest(arg1) {
  return window['go']['app']['App']['StartupForTest'](arg1);
}
