// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {app} from '../models';
import {context} from '../models';

export function AssetsHandlerForTest():Promise<http.Handler>;

export function ResolveLive(arg1:number,arg2:string):Promise<app.resolveResult>;

export function SetClientSize(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function StartupForTest(arg1:context.Context):Promise<void>;
